In [2]:
import torch.nn.functional as F
import torch
import const

In [33]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
# mask for x > 3
mask = x > 3
mask.long()

tensor([0, 0, 0, 1, 1])

In [29]:
x1 = torch.rand(3, 10)
x2 = torch.rand(3, 10)

x1, x2

(tensor([[0.6285, 0.8788, 0.7594, 0.3864, 0.0241, 0.8997, 0.2038, 0.3077, 0.7559,
          0.5350],
         [0.4771, 0.1329, 0.3856, 0.1060, 0.3944, 0.8548, 0.0074, 0.2071, 0.5467,
          0.9779],
         [0.1516, 0.3221, 0.2558, 0.1680, 0.2598, 0.1094, 0.7371, 0.9272, 0.2588,
          0.6011]]),
 tensor([[0.3132, 0.0901, 0.9686, 0.4977, 0.6566, 0.5024, 0.8000, 0.9769, 0.7754,
          0.4353],
         [0.7683, 0.8182, 0.5016, 0.7702, 0.5113, 0.0496, 0.4986, 0.4898, 0.1801,
          0.0707],
         [0.0608, 0.4091, 0.4280, 0.1229, 0.5518, 0.5713, 0.5903, 0.3287, 0.5112,
          0.4265]]))

In [30]:
out = torch.stack([x1, x2], dim=1)
out.shape, out

(torch.Size([3, 2, 10]),
 tensor([[[0.6285, 0.8788, 0.7594, 0.3864, 0.0241, 0.8997, 0.2038, 0.3077,
           0.7559, 0.5350],
          [0.3132, 0.0901, 0.9686, 0.4977, 0.6566, 0.5024, 0.8000, 0.9769,
           0.7754, 0.4353]],
 
         [[0.4771, 0.1329, 0.3856, 0.1060, 0.3944, 0.8548, 0.0074, 0.2071,
           0.5467, 0.9779],
          [0.7683, 0.8182, 0.5016, 0.7702, 0.5113, 0.0496, 0.4986, 0.4898,
           0.1801, 0.0707]],
 
         [[0.1516, 0.3221, 0.2558, 0.1680, 0.2598, 0.1094, 0.7371, 0.9272,
           0.2588, 0.6011],
          [0.0608, 0.4091, 0.4280, 0.1229, 0.5518, 0.5713, 0.5903, 0.3287,
           0.5112, 0.4265]]]))

In [20]:
F.cross_entropy(sim_matrix, contr_labels), torch.nn.CrossEntropyLoss()(sim_matrix, contr_labels)   

(tensor(1.9749), tensor(1.9749))